# Purple Future Minimal — Kitty

font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.5

window_padding_width 10
placement_strategy center
hide_window_decorations yes
confirm_os_window_close 0
enable_audio_bell no

background_opacity 0.86
dynamic_background_opacity yes
background_blur 32

cursor_shape beam
cursor_beam_thickness 1.5
cursor_blink_interval 0.6

foreground #f4efff
background #0b0814
selection_foreground #0b0814
selection_background #c77dff

cursor #c77dff
cursor_text_color #0b0814
url_color #7df9ff

active_tab_foreground #f4efff
active_tab_background #30204e
inactive_tab_foreground #a797c4
inactive_tab_background #151027
tab_bar_background #0b0814

tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted

# ANSI palette
color0  #0b0814
color1  #ff5c8a
color2  #8affc1
color3  #f9dc5c
color4  #7df9ff
color5  #c77dff
color6  #9d4edd
color7  #f4efff
color8  #57446f
color9  #ff7aa2
color10 #a3ffd1
color11 #ffe979
color12 #9ffcff
color13 #d7a1ff
color14 #b37dff
color15 #ffffff

map ctrl+shift+enter new_window_with_cwd
map ctrl+shift+t new_tab_with_cwd
map ctrl+shift+h previous_tab
map ctrl+shift+l next_tab
